<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CasCap.Api.Azure.Auth" Version="1.6.3" />
    <PackageVersion Include="CasCap.Api.Azure.CognitiveServices" Version="1.6.3" />
    <PackageVersion Include="CasCap.Common.Abstractions" Version="4.14.2" />
    <PackageVersion Include="CasCap.Common.Configuration" Version="4.14.2" />
    <PackageVersion Include="CasCap.Common.Extensions" Version="4.14.2" />
    <PackageVersion Include="CasCap.Common.Net" Version="4.14.2" />
    <PackageVersion Include="CasCap.Common.Services" Version="4.14.2" />
    <PackageVersion Include="CasCap.Common.Testing" Version="4.14.2" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
